# Build

ifndef MCU
    MCU = atxmega32a4u
endif

C_SRC += # extra includes

CDEFS += -DNRF24_CE_PORT=PORTR
CDEFS += -DNRF24_CE_PIN=PIN0_bm

CDEFS += -DNRF24_IRQ_PORT=PORTR
CDEFS += -DNRF24_IRQ_PIN=PIN1_bm

CDEFS += -DCHECK_PORT=PORTE
CDEFS += -DCHECK_PIN=PIN1_bm
CDEFS += -DCHECK_PIN_VECT=PORTE_INT0_vect

VID = 6666
PID = 1111

USE_USB := 1
USE_SCANNER := 1
USE_NRF24 := 1
USE_CHECK_PIN := 1
USE_I2C := 1
USE_HARDWARE_SPECIFIC_SCAN := 0
