ifndef MCU
    MCU = atxmega64a4u
endif

C_SRC += $(BOARD_DIR)/alpha_split/alpha_split_util.c

CDEFS += -DCHECK_PORT=PORTC
CDEFS += -DCHECK_PIN=PIN1_bm

# VBUS_CHECK pin on pin C1
# CDEFS += -DI2C_LEFT_PORT=PORTR
# CDEFS += -DI2C_LEFT_PIN=PIN0_bm

# CDEFS += -DI2C_RIGHT_PORT=PORTE
# CDEFS += -DI2C_RIGHT_PIN=PIN3_bm

# CDEFS += -DUSB_SEL_PORT=PORTE
# CDEFS += -DUSB_SEL_PIN=PIN2_bm

# CDEFS += -DUSB_OE_PORT=PORTR
# CDEFS += -DUSB_OE_PIN=PIN1_bm

#### v2
# Note: USB_SEL is connected to I2C_OE_LEFT
CDEFS += -DALPHA_SPLIT_V2
CDEFS += -DI2C_OE_LEFT_PORT=PORTR
CDEFS += -DI2C_OE_LEFT_PIN=PIN0_bm

CDEFS += -DI2C_OE_RIGHT_PORT=PORTE
CDEFS += -DI2C_OE_RIGHT_PIN=PIN3_bm

CDEFS += -DUSB_OE_PORT=PORTR
CDEFS += -DUSB_OE_PIN=PIN1_bm
