# Build settings for alpha_split

ifndef MCU
    MCU = atxmega64a4u
endif

C_SRC += boards/alpha_split/alpha_split_util.c

CDEFS += -DDUAL_USB=1

CDEFS += -DVBUS_PIN_PORT=C
CDEFS += -DVBUS_PIN_NUM=1
CDEFS += -DVBUS_PIN_INT_NUM=1

CDEFS += -DNRF24_IRQ_PIN_PORT=B
CDEFS += -DNRF24_IRQ_PIN_NUM=3
CDEFS += -DNRF24_IRQ_INT_NUM=1

# VBUS_CHECK pin on pin C1
# CDEFS += -DI2C_LEFT_PORT=PORTR
# CDEFS += -DI2C_LEFT_PIN=PIN0_bm

# CDEFS += -DI2C_RIGHT_PORT=PORTE
# CDEFS += -DI2C_RIGHT_PIN=PIN3_bm

# CDEFS += -DUSB_SEL_PORT=PORTE
# CDEFS += -DUSB_SEL_PIN=PIN2_bm

# CDEFS += -DUSB_OE_PORT=PORTR
# CDEFS += -DUSB_OE_PIN=PIN1_bm

#### v2
# Note: USB_SEL is connected to I2C_OE_LEFT
CDEFS += -DALPHA_SPLIT_V2
CDEFS += -DI2C_OE_LEFT_PORT=PORTR
CDEFS += -DI2C_OE_LEFT_PIN=PIN0_bm

CDEFS += -DI2C_OE_RIGHT_PORT=PORTE
CDEFS += -DI2C_OE_RIGHT_PIN=PIN3_bm

CDEFS += -DUSB_OE_PORT=PORTR
CDEFS += -DUSB_OE_PIN=PIN1_bm

CDEFS += -DNRF24_CE_PORT=PORTB
CDEFS += -DNRF24_CE_PIN=PIN2_bm

VID = 6666
PID = 1111

USE_CHECK_PIN := 1
USE_USB := 1
USE_SCANNER := 1
USE_NRF24 := 0
USE_I2C := 1
USE_HARDWARE_SPECIFIC_SCAN := 0
