ifndef LAYOUT_FILE
    LAYOUT_FILE=$(KEYPLUS_PATH)/../layouts/nrf52_4key.yaml
endif

MCU = nrf52840
MCU_STRING = nRF52840_QIAA
NRF52_LINK_SCRIPT := $(BOARD_DIR)/$(BOARD)/keyplus_gcc_nrf52840.ld

USE_USB := 1
USE_SCANNER := 1
USE_NRF24 := 1
USE_UNIFYING := 1
USE_CHECK_PIN := 0
USE_I2C := 0
